#!/usr/bin/env python3

#
# Copyright (C) 2022 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import json
import sys
import agent
import os
from agent.ldapproxy import Ldapproxy

request = json.load(sys.stdin)

odom = Ldapproxy().get_domain(request['user_domain'])
if odom is None:
    # validation error
    agent.set_status('validation-failed')
    json.dump([{'field':'user_domain', 'parameter':'user_domain','value': request['user_domain'], 'error':'domain_not_found'}], fp=sys.stdout)
    sys.exit(2)
