#!/bin/bash

#
# Copyright (C) 2022 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

exec 1>&2

systemctl --user --now enable rspamd.service
systemctl --user --now enable clamav.service

# XXX: Unconditionally enable and start ClamAV unofficial sigs. This
# enforcment should be subject to some condition and preserved after
# restore-module and clone-module.
systemctl --user --now enable clamav-unofficial-sigs.timer
systemctl --user --now enable --no-block clamav-unofficial-sigs.service

systemctl --user enable dovecot.service
systemctl --user reload-or-restart dovecot.service

systemctl --user enable postfix.service
systemctl --user reload-or-restart postfix.service
