#!/bin/bash

#
# Copyright (C) 2022 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

exec 1>&2

systemctl --user --now enable clamav.service
systemctl --user --now enable rspamd.service

systemctl --user --now enable clamav-unofficial-sigs.timer

systemctl --user enable dovecot.service
systemctl --user reload-or-restart dovecot.service

systemctl --user enable postfix.service
systemctl --user reload-or-restart postfix.service
