#!/usr/bin/env python3

#
# Copyright (C) 2022 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import sys
import agent.tasks
import os
import agent

agent_id = agent.resolve_agent_id('traefik@node')
mail_hostname = os.environ['MAIL_HOSTNAME']

agent.tasks.run_nowait(
    agent_id=agent_id, # e.g. module/traefik1
    action='set-certificate',
    data={
        "fqdn":mail_hostname,
        "sync": True,
    },
    parent='', # Run as a root task
    extra={
        'title': 'set-certificate',
        'isNotificationHidden': False,
    },
)
