#!/usr/bin/env python3

#
# Copyright (C) 2022 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

import json
import sys
import agent
import mail
from sqlite3 import IntegrityError

request = json.load(sys.stdin)
sdb = mail.pcdb_connect()
mbxn = request['mailbox']
rights_map = mail.get_rights_map()

try:

    # Drop address records related to this mailbox
    cur = sdb.cursor()
    cur.execute("""DELETE FROM destmap WHERE alocal = :alocal AND domain = :domain AND dest = :dest""",
        {'alocal':mbxn, 'domain':"*", 'dest':"vmail+" + mbxn})
    cur.execute("""DELETE FROM addresses WHERE alocal = :alocal AND domain = :domain"""
        """ AND (SELECT COUNT(*) FROM destmap AS d WHERE d.alocal = :alocal AND d.domain = :domain) = 0""", 
        {'alocal':mbxn, 'domain':"*"})

    # Destroy the mailbox and its contents
    mail.doveadm_query("mailboxDelete", {"mailbox": [mbxn], "user": "vmail"})

except mail.DoveadmError as dex:
    if dex.code != 68:
        raise

    agent.set_status('validation-failed')
    json.dump([{'field':'mailbox', 'parameter':'mailbox','value': mbxn, 'error':'mailbox_not_found'}], fp=sys.stdout)
    sys.exit(3)

else:
    sdb.commit()

finally:
    sdb.close()
