#!/usr/bin/env python3

#
# Copyright (C) 2023 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import json
import sys
import agent
import mail
from sqlite3 import IntegrityError

request = json.load(sys.stdin)
sdb = mail.pcdb_connect()
mbxn = request['mailbox']
rights_map = mail.get_rights_map()

try:

    # Drop address records related to this mailbox
    cur = sdb.cursor()
    cur.execute("""DELETE FROM destmap WHERE alocal = :alocal AND domain = :domain AND dest = :dest""",
        {'alocal':mbxn, 'domain':"*", 'dest':"vmail+" + mbxn})
    cur.execute("""DELETE FROM addresses WHERE alocal = :alocal AND domain = :domain"""
        """ AND (SELECT COUNT(*) FROM destmap AS d WHERE d.alocal = :alocal AND d.domain = :domain) = 0""", 
        {'alocal':mbxn, 'domain':"*"})

    # Destroy the mailbox and its contents
    mail.doveadm_query("mailboxDelete", {"mailbox": [mbxn], "user": "vmail", "recursive": True})

except mail.DoveadmError as dex:
    if dex.code != 68:
        raise

    agent.set_status('validation-failed')
    json.dump([{'field':'mailbox', 'parameter':'mailbox','value': mbxn, 'error':'mailbox_not_found'}], fp=sys.stdout)
    sys.exit(3)

else:
    sdb.commit()

finally:
    sdb.close()
