#!/usr/bin/env python3

#
# Copyright (C) 2022 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

import json
import sys
import agent
import mail

class AddressNotFoundError(Exception):
    pass

request = json.load(sys.stdin)

sdb = mail.pcdb_connect()

local = request['local']
if request['atype'] == "domain":
    domain = request['domain']
elif request['atype'] == "wildcard":
    domain = "*"
else:
    raise Exception(f"Unexpected atype {request['atype']} value")

# RFC-mandatory address, cannot be deleted.
if local == "postmaster" and domain == "*":
    agent.set_status('validation-failed')
    json.dump([{'field':'local', 'parameter':'local','value': 'postmaster', 'error':'address_removal_forbidden'}], fp=sys.stdout)
    sys.exit(3)

try:
    cur = sdb.cursor()
    cur.execute("""DELETE FROM addresses WHERE alocal=? AND domain=?""", (local, domain,))
    if cur.rowcount == 0:
        raise AddressNotFoundError

    cur.execute("""DELETE FROM destmap WHERE alocal=? AND domain=?""", (local, domain,))
    if cur.rowcount == 0:
        raise AddressNotFoundError

except AddressNotFoundError:
    sdb.rollback()
    agent.set_status('validation-failed')
    json.dump([{'field':'local', 'parameter':'local','value': request['local'], 'error':'address_not_found'}], fp=sys.stdout)
    sys.exit(2)

else:
    sdb.commit()
finally:
    sdb.close()
