#
# ldapconf.sh -- LDAP settings for shell scripts
# This file is eval'd
#

DOVECOT_LDAP_HOST=${DOVECOT_LDAP_HOST}
DOVECOT_LDAP_PORT=${DOVECOT_LDAP_PORT}
DOVECOT_LDAP_USER=${DOVECOT_LDAP_USER}
DOVECOT_LDAP_PASS=${DOVECOT_LDAP_PASS}
DOVECOT_LDAP_BASE=${DOVECOT_LDAP_BASE}
DOVECOT_LDAP_SCHEMA=${DOVECOT_LDAP_SCHEMA}
