#!/usr/bin/env python3

#
# Copyright (C) 2023 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import json
import sys
import mail
import os

mail.abort_with_json_if_not_configured([])

mailboxes = {}

rights_map = mail.get_rights_map()

def get_acls(mbxn):
    lacls = []
    for dacl in mail.doveadm_query("aclGet", {"user": "vmail", "mailbox": mbxn}):
        rights_set = set(dacl['rights'].split(" "))
        if dacl['id'].startswith('user='):
            idx = dacl['id'].removeprefix('user=')
            oacl = {
                "stype": "user",
                "subject": mail.mailbox_to_destination(idx),
            }
        elif dacl['id'] == 'group=vmail':
            continue # skip default ACLs for the vmail master user
        elif dacl['id'].startswith('group='):
            idx = dacl['id'].removeprefix('group=')
            oacl = {
                "stype": "group",
                "subject": mail.mailbox_to_destination(idx),
            }
        else:
            oacl = {
                "stype": "none",
                "subject": {
                    "dtype": "apo",
                    "name": dacl['id'],
                }
            }

        for xright in rights_map:
            if rights_set == rights_map[xright]:
                oacl['rights'] = {
                    "rtype": xright,
                    "values": list(rights_set),
                }
                break
        else:
            rights_set.discard("-") # ignore bogus right value
            oacl['rights'] = {
                "rtype": "custom",
                "values": list(rights_set),
            }

        lacls.append(oacl)

    return lacls

for mbxn in mail.get_public_mailboxes():
    mailboxes[mbxn] = {
        "mailbox": mbxn,
        "acls": get_acls(mbxn),
    }

json.dump(list(mailboxes.values()), fp=sys.stdout, cls=mail.DestEncoder)
