#!/usr/bin/env python3

#
# Copyright (C) 2022 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import json
import sys
import agent

json.dump({
    "username": "vmail",
    "password": agent.read_envfile('dovecot.env')['DOVECOT_VMAIL_PASS'],
}, fp=sys.stdout)
