#!/usr/bin/env python3

#
# Copyright (C) 2024 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import json
import sys
import os

config = {}

config['bcc'] = os.environ.get('POSTFIX_ALWAYS_BCC','')

json.dump(config, fp=sys.stdout)
