#!/usr/bin/env python3

#
# Copyright (C) 2022 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

import json
import sys
import agent
import os

event = json.load(sys.stdin)

if str(event['node']) != os.environ['NODE_ID']:
    print(agent.SD_DEBUG + "Event ignored: source is another node")
    sys.exit(2)

if event['domain']['main'] != os.environ['MAIL_HOSTNAME']:
    print(agent.SD_DEBUG + "Event ignored: the certificate does not match our hostname")
    sys.exit(3)
