#!/bin/bash

#
# Copyright (C) 2022 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

if systemctl --user -q is-active dovecot; then
    install-certificate dovecot && podman exec dovecot dovecot reload
fi

if systemctl --user -q is-active postfix; then
    install-certificate postfix && podman exec postfix postfix reload
fi
