#!/usr/bin/env python3

#
# Copyright (C) 2022 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import json
import sys
import mail
import agent

request = json.load(sys.stdin)

if request['domain'] == '*':
    agent.set_status('validation-failed')
    json.dump([{'field': 'domain', 'parameter': 'domain', 'value': request['domain'], 'error':'domain_removal_forbidden'}], fp=sys.stdout)
    sys.exit(3)

class DomainNotFoundError(Exception):
    pass

sdb = mail.pcdb_connect()
try:
    cur = sdb.cursor()
    cur.execute("""DELETE FROM addresses WHERE domain=?""", (request['domain'],))
    cur.execute("""DELETE FROM destmap WHERE domain=?""", (request['domain'],))
    cur.execute("""DELETE FROM domains WHERE domain=?""", (request['domain'],))
    if cur.rowcount == 0:
        raise DomainNotFoundError()

except DomainNotFoundError:
    sdb.rollback()
    agent.set_status('validation-failed')
    json.dump([{'field': 'domain', 'parameter': 'domain', 'value': request['domain'], 'error':'domain_not_found'}], fp=sys.stdout)
    sys.exit(2)

else:
    sdb.commit()

finally:
    sdb.close()
