#!/usr/bin/env python3

#
# Copyright (C) 2022 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

import json
import sys
import mail
import agent

request = json.load(sys.stdin)

if request['domain'] == '*':
    agent.set_status('validation-failed')
    json.dump([{'field': 'domain', 'parameter': 'domain', 'value': request['domain'], 'error':'domain_removal_forbidden'}], fp=sys.stdout)
    sys.exit(3)

class DomainNotFoundError(Exception):
    pass

sdb = mail.pcdb_connect()
try:
    cur = sdb.cursor()
    cur.execute("""DELETE FROM addresses WHERE domain=?""", (request['domain'],))
    cur.execute("""DELETE FROM destmap WHERE domain=?""", (request['domain'],))
    cur.execute("""DELETE FROM domains WHERE domain=?""", (request['domain'],))
    if cur.rowcount == 0:
        raise DomainNotFoundError()

except DomainNotFoundError:
    sdb.rollback()
    agent.set_status('validation-failed')
    json.dump([{'field': 'domain', 'parameter': 'domain', 'value': request['domain'], 'error':'domain_not_found'}], fp=sys.stdout)
    sys.exit(2)

else:
    sdb.commit()

finally:
    sdb.close()
