#!/usr/bin/env python3

#
# Copyright (C) 2023 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import json
import sys
import mail
import agent
from sqlite3 import IntegrityError

class RelayNotFoundError(Exception):
    pass

request = json.load(sys.stdin)

sdb = mail.pcdb_connect()
rule_type = request['rule_type']
rule_subject = request['rule_subject']
password = request['password']

def get_password_from_database(rule_subject):
    # Function to query the database for the password based on sender or recipient
    sdb = mail.pcdb_connect()
    cur = sdb.cursor()
    cur.execute("SELECT password FROM relayrules WHERE rule_subject=?", (rule_subject,))
    result = cur.fetchone()
    sdb.close()
    if result:
        return result[0]
    else:
        agent.set_status('validation-failed')
        json.dump([{'field':'test_rule_credentials','parameter':'test_rule_credentials','value':'cannot_retrieve_password_user_from_sqlite','error':'cannot_retrieve_password_user_from_sqlite'}],fp=sys.stdout, default=str)
        sys.exit(3)

# password not changed, we need to retrieve it from the database
if password == '':
    password = get_password_from_database(rule_subject)

try:
    cur = sdb.cursor()

    if 'host' in request:
        cur.execute("""UPDATE relayrules SET host=? WHERE rule_subject=?""", (request['host'], rule_subject))

    if 'port' in request:
        cur.execute("""UPDATE relayrules SET port=? WHERE rule_subject=?""", (request['port'], rule_subject))

    if 'mandatory_tls' in request:
        cur.execute("""UPDATE relayrules SET tls=? WHERE rule_subject=?""", ('encrypt' if request['mandatory_tls'] else 'may', rule_subject))

    if 'username' in request:
        cur.execute("""UPDATE relayrules SET username=? WHERE rule_subject=?""", (request['username'], rule_subject))

    if 'password' in request:
        cur.execute("""UPDATE relayrules SET password=? WHERE rule_subject=?""", (password, rule_subject))

    if 'enabled' in request:
        cur.execute("""UPDATE relayrules SET enabled=? WHERE rule_subject=?""", (1 if request['enabled'] else 0, rule_subject))

    if cur.rowcount == 0:
        raise RelayNotFoundError()

except RelayNotFoundError:
    sdb.rollback()
    agent.set_status('validation-failed')
    json.dump([{'field': 'rule_subject', 'parameter': 'subject', 'value': rule_subject, 'error':'relay_not_found'}], fp=sys.stdout)
    sys.exit(2)

else:
    sdb.commit()

finally:
    sdb.close()
