#!/usr/bin/env python3

#
# Copyright (C) 2022 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import json
import sys
import mail
from sqlite3 import OperationalError

mail.abort_with_json_if_not_configured([])

try:
    domains = mail.get_domains()
except OperationalError:
    domains = {}

json.dump(list(domains.values()), fp=sys.stdout, cls=mail.DestEncoder)
