#!/usr/bin/env python3

#
# Copyright (C) 2023 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import json
import sys
import agent

request = json.load(sys.stdin)

maximal_queue_lifetime = int(request['maximal_queue_lifetime'])
agent.set_env("POSTFIX_MAXIMAL_QUEUE_LIFETIME", maximal_queue_lifetime)

