#!/usr/bin/env python3

#
# Copyright (C) 2024 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import json
import sys
import mail
from sqlite3 import OperationalError

mail.abort_with_json_if_not_configured([])

sdb = mail.pcdb_connect(readonly=True)

relays = []
has_wildcard =  False
try:
    for row in sdb.execute("""SELECT sender, dest,  host, port, tls, username, password, enabled, rdesc FROM relayrules"""):
        if row['sender'] is not None:
            sender = row['sender']
            relays.append({
                'sender': row['sender'],
                'host': row['host'],
                'port': row['port'],
                'tls': row['tls'] == "encrypt",
                'username': row['username'],
                'has_password': True if row['password'] != '' else False,
                'enabled': row['enabled'] == 1
            })
        elif row['dest'] is not None:
            recipient = row['dest']
            if recipient == '*':
                has_wildcard = True
            relays.append({
                'recipient': row['dest'],
                'host': row['host'],
                'port': row['port'],
                'tls': row['tls'] == "encrypt",
                'username': row['username'],
                'has_password': True if row['password'] != '' else False,
                'enabled': row['enabled'] == 1
            })
except OperationalError:
    relays = []

# we want to order rules by sender, recipient, wildcard
def custom_sort(rule):
    # If it's a sender rule
    if 'sender' in rule:
        # Sort by email first, then domain
        if '@' in rule['sender']:
            return (0, rule['sender'])
        else:
            return (1, rule['sender'])
    # If it's a recipient rule
    elif 'recipient' in rule:
        # Sort by email first, then domain
        if rule['recipient'] == '*':
            return (4, '')
        elif '@' in rule['recipient']:
            return (2, rule['recipient'])
        else:
            return (3, rule['recipient'])
sorted_rules = sorted(relays, key=custom_sort)

output= {"has_wildcard": has_wildcard, "rules": sorted_rules}

json.dump(output, fp=sys.stdout)
