#!/bin/ash

#
# Copyright (C) 2023 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

# shellcheck shell=dash

set -e

sig_type=${1:?Invocation error: the first argument must be either \"freshclam\" or \"cus\"}
shift # discard first argument

# Wait for clamd to become available, ignoring connection errors.
clamdscan --ping 60:5 >/dev/null 2>&1

if [ "${sig_type}" = "freshclam" ]; then
    # Start freshclam
    exec /usr/bin/freshclam "${@}"
fi

sig_type_lc=$(printf '%s' "${sig_type}" | tr 'A-Z' 'a-z')

case "${sig_type_lc}" in
    cus*)
        case "${sig_type_lc}" in
            cus-*)
                # Change configured rating value in user.conf before starting
                # the download process. If sig_type has no rating suffix, do
                # not touch it.
                set-cus-rating "${sig_type_lc#cus-}"
                ;;
        esac
        # Start clamav-unofficial-sigs
        exec su -s /bin/bash - clamav /usr/local/sbin/clamav-unofficial-sigs.sh -- "${@}"
        ;;
esac
