#!/bin/ash

#
# Copyright (C) 2022 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

# shellcheck shell=dash

set -e

sig_type=${1:?Invocation error: the first argument must be either \"freshclam\" or \"cus\"}
shift # discard first argument

# Wait for clamd to become available, ignoring connection errors.
clamdscan --ping 60:5 >/dev/null 2>&1

if [ "${sig_type}" = "freshclam" ]; then
    # Start freshclam
    exec /usr/bin/freshclam "${@}"
fi

if [ "${sig_type}" = "cus" ]; then
    cfg_dir="/etc/clamav-unofficial-sigs"
    # Copy override files for clamav-unofficial-sigs:
    for cfg_file in additional_dbs.txt master.conf user.conf os.conf; do
        if [ -f "${cfg_dir}/override.d/${cfg_file}" ]; then
            echo "Applying ${cfg_dir}/override.d/${cfg_file}"
            cat "${cfg_dir}/${cfg_file}" > "${cfg_dir}/${cfg_file}.orig"
            cat "${cfg_dir}/override.d/${cfg_file}" > "${cfg_dir}/${cfg_file}"
        elif [ -f "${cfg_dir}/${cfg_file}.orig" ]; then
            echo "Restoring ${cfg_dir}/${cfg_file}.orig"
            mv -v "${cfg_dir}/${cfg_file}.orig" "${cfg_dir}/${cfg_file}"
        fi
    done
    # Start clamav-unofficial-sigs
    exec su -s /bin/bash - clamav /usr/local/sbin/clamav-unofficial-sigs.sh -- "${@}"
fi
