#!/bin/ash

#
# Copyright (C) 2023 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

# shellcheck shell=dash
set -e

rating=${1:?missing rating argument}
rating=$(printf '%s' "${rating}" | tr 'a-z' 'A-Z')

sed -i "/^default_dbs_rating=/ c \default_dbs_rating=\"${rating}\"" \
    /etc/clamav-unofficial-sigs/user.conf
    /etc/clamav-unofficial-sigs/user.conf
