#!/usr/bin/env python3

#
# Copyright (C) 2022 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

import json
import sys
import mail
from sqlite3 import OperationalError

adduser_domains = []
addgroup_domains = []
laddresses = []

try:
    sdb = mail.pcdb_connect(readonly=True)

    for row in sdb.execute("""SELECT domain FROM domains WHERE addusers=1"""):
        adduser_domains.append(row['domain'])

    for row in sdb.execute("""SELECT domain FROM domains WHERE addgroups=1"""):
        addgroup_domains.append(row['domain'])

    laddresses = list(mail.get_addresses().values())

except OperationalError:
    pass

except KeyError:
    pass

json.dump({
    "adduser_domains": adduser_domains,
    "addgroup_domains": addgroup_domains,
    "addresses": laddresses,
}, fp=sys.stdout, cls=mail.DestEncoder)
