#!/usr/bin/env python3

#
# Copyright (C) 2023 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import json
import sys
import agent

request = json.load(sys.stdin)
queue = request['queue']
action = request['action']

if action == 'resend':
    agent.run_helper("podman", "exec", "postfix", "postqueue", "-i", queue).check_returncode()
elif action == 'resend_all':
    agent.run_helper("podman", "exec", "postfix", "postqueue", "-f").check_returncode()
elif action == 'delete':
    agent.run_helper("podman", "exec", "postfix", "postsuper", "-d", queue).check_returncode()
elif action == 'delete_all':
    agent.run_helper("podman", "exec", "postfix", "postsuper", "-d", "ALL").check_returncode()
else:
    sys.exit(2)