#!/usr/bin/env python3

#
# Copyright (C) 2023 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import json
import sys
import mail
import agent

request = json.load(sys.stdin)

sender=request.get('sender')
recipient=request.get('recipient')

class RelayNotFoundError(Exception):
    pass

sdb = mail.pcdb_connect()
try:
    cur = sdb.cursor()
    if sender:
        cur.execute("""DELETE FROM relayrules WHERE sender=?""", (sender,))
    elif recipient:
        cur.execute("""DELETE FROM relayrules WHERE dest=?""", (recipient,))
    if cur.rowcount == 0:
        raise RelayNotFoundError()

except RelayNotFoundError:
    sdb.rollback()
    agent.set_status('validation-failed')
    if sender:
        json.dump([{'field': 'sender', 'parameter': 'sender', 'value': sender, 'error':'sender_not_found'}], fp=sys.stdout)
    elif recipient:
        json.dump([{'field': 'recipient', 'parameter': 'recipient', 'value': recipient, 'error':'recipient_not_found'}], fp=sys.stdout)
    sys.exit(2)

else:
    sdb.commit()

finally:
    sdb.close()
