#!/usr/bin/env python3

#
# Copyright (C) 2023 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import json
import sys
import mail
import agent

request = json.load(sys.stdin)

rule_subject = request['rule_subject']

class RelayNotFoundError(Exception):
    pass

sdb = mail.pcdb_connect()
try:
    cur = sdb.cursor()
    cur.execute("""DELETE FROM relayrules WHERE rule_subject=?""", (rule_subject,))
    if cur.rowcount == 0:
        raise RelayNotFoundError()

except RelayNotFoundError:
    sdb.rollback()
    agent.set_status('validation-failed')
    json.dump([{'field': 'rule_subject', 'parameter': 'rule_subject', 'value': rule_subject, 'error':'rule_subject_not_found'}], fp=sys.stdout)
    sys.exit(2)

else:
    sdb.commit()

finally:
    sdb.close()
