#!/usr/bin/env python3

#
# Copyright (C) 2023 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import json
import sys
import mail
import agent
from sqlite3 import IntegrityError

request = json.load(sys.stdin)

sdb = mail.pcdb_connect()
sender = request.get('sender')
dest = request.get('dest')

try:
    values = {
        "sender": sender,
        "dest": dest,
        "host": request['host'],
        "port": request['port'],
        "mandatory_tls": 'encrypt' if request.get("mandatory_tls", False) else 'may',
        "username": request.get("username", ""),
        "password": request.get("password", ""),
        "enabled": 1 if request.get("enabled", True) else 0,
        "rdesc": request.get("description", ""),
    }

    cur = sdb.cursor()
    if sender:
        # ensure that the sender does not exist
        cur.execute("SELECT * FROM relayrules WHERE sender = ?", (sender,))
        row = cur.fetchone()
        if row:
            agent.set_status('validation-failed')
            json.dump([{'field':'sender', 'parameter':'sender','value': sender, 'error':'sender_already_exist'}], fp=sys.stdout)
            sys.exit(4)

        cur.execute("""INSERT INTO relayrules (sender, host, port, tls, username, password, enabled, rdesc) VALUES (:sender, :host, :port, :tls, :username, :password, :enabled, :rdesc)""", values)
 
    elif dest:
        # ensure that the dest does not exist
        cur.execute("SELECT * FROM relayrules WHERE dest = ?", (dest,))
        row = cur.fetchone()
        if row:
            agent.set_status('validation-failed')
            json.dump([{'field':'dest', 'parameter':'dest','value': dest, 'error':'dest_already_exist'}], fp=sys.stdout)
            sys.exit(4)

        cur.execute("""INSERT INTO relayrules (dest, host, port, tls, username, password, enabled, rdesc) VALUES (:dest, :host, :port, :tls, :username, :password, :enabled, :rdesc)""", values)

except IntegrityError:
    sdb.rollback()
    # The domain already exists
    agent.set_status('validation-failed')
    if sender:
        json.dump([{'field':'sender', 'parameter':'sender','value': sender, 'error':'sender_already_exist'}], fp=sys.stdout)
    elif dest:
        json.dump([{'field':'dest', 'parameter':'dest','value': dest, 'error':'dest_already_exist'}], fp=sys.stdout)
    sys.exit(3)

else:
    sdb.commit()

finally:
    sdb.close()
