#!/usr/bin/env python3

# Copyright (C) 2024 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#


import agent
import agent.tasks
import os
import sys
import json



data = json.load(sys.stdin)

sender = data.get('sender')
recipient = data.get('recipient')
# we cannot have both sender and recipient at the time
if recipient and sender:
    agent.set_status('validation-failed')
    json.dump([{'field':'sender','parameter':'sender','value':sender,'error':'cannot_be_sender_and_recipient'}],fp=sys.stdout, default=str)
    sys.exit(3)
