#!/bin/bash

#
# Copyright (C) 2022 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

set -e    # exit immediately if an error occurs
exec 1>&2 # ensure any output is sent to stderr

#
# Allow other modules to read the Dovecot master password
#
redis-exec SADD "${AGENT_ID}/roles/mailadm" "reveal-master-credentials"
