#!/bin/bash

#
# Copyright (C) 2023 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

set -e    # exit immediately if an error occurs
exec 1>&2 # ensure any output is sent to stderr

#
# Allow other modules to read the Dovecot master password and read the
# module configuration
#
redis-exec SADD "${AGENT_ID}/roles/mailadm" "reveal-master-credentials" "get-*" "list-*"
# Piler must be able to make a relay remotely
redis-exec SADD "${AGENT_ID}/roles/mailadm" "set-bcc-piler" "add-relay-rule" "alter-relay-rule" "remove-relay-rule"

#
# Allow the instance itself to run some subtasks during restore and clone actions
#
redis-exec SADD "${AGENT_ID}/roles/selfadm" \
    "configure-module" \
    "set-filter-configuration" \
    "set-mailbox-settings" \
    "set-master-users"
