#!/bin/bash

#
# Copyright (C) 2022 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

set -e    # exit immediately if an error occurs
exec 1>&2 # ensure any output is sent to stderr

systemctl --user --now enable clamav.service

# Enable unofficial signatures by default
systemctl --user enable --now clamav-unofficial-sigs.timer
systemctl --user enable --now --no-block clamav-unofficial-sigs.service
