#!/bin/bash

#
# Copyright (C) 2023 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

set -e    # exit immediately if an error occurs
exec 1>&2 # ensure any output is sent to stderr

/usr/bin/podman run \
    --detach \
    --name=configure_solr \
    --rm \
    --volume=solr-data:/var/solr:Z \
    ${SOLR_IMAGE} \
    solr-precreate dovecot

/usr/bin/podman exec configure_solr rm -f /var/solr/data/dovecot/conf/{schema.xml,managed-schema.xml,solrconfig.xml}

/usr/bin/podman stop configure_solr
