#!/usr/bin/env python3

#
# Copyright (C) 2023 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import agent
import os

agent.add_public_service(os.environ['MODULE_ID'], [
    "25/tcp", # SMTP
    "110/tcp", # POP3
    "143/tcp", # IMAP
    "993/tcp", # IMAPs
    "995/tcp", # POP3s
    "587/tcp", # Submission
    "465/tcp", # Submissions
])

# Ignore exit code
