#!/usr/bin/env python3

#
# Copyright (C) 2022 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

import agent
import os

agent.add_public_service(os.environ['MODULE_ID'], [
    "25/tcp", # SMTP
    "110/tcp", # POP3
    "143/tcp", # IMAP
    "993/tcp", # IMAPs
    "995/tcp", # POP3s
    "587/tcp", # Submission
    "465/tcp", # Submissions
])

# Ignore exit code
