#!/usr/bin/env python3

#
# Copyright (C) 2022 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import json
import sys
import os

if os.getenv("DOVECOT_MASTER_USERS"):
    master_users = os.getenv("DOVECOT_MASTER_USERS").split(",")
else:
    master_users = []

json.dump({
    "master_users": master_users
}, fp=sys.stdout)
