#!/usr/bin/env python3

#
# Copyright (C) 2022 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

import json
import sys
import os
import agent
from agent.ldapclient import Ldapclient
from agent.ldapproxy import Ldapproxy

hdest = {}

try:
    dconf = Ldapproxy().get_domain(os.environ['POSTFIX_ORIGIN'])
    agent.assert_exp(dconf is not None) # Ensure the user domain exists
    ldapclient = Ldapclient.factory(**dconf)

    for euser in ldapclient.list_users():
        hdest[euser['user']] = {
            'dtype': 'user',
            'name': euser['user'],
            'ui_name': euser['display_name'],
        }

    for egroup in ldapclient.list_groups():
        hdest[egroup['group']] = {
            'dtype': 'group',
            'name': egroup['group'],
            'ui_name': egroup['description'],
        }

except KeyError as kex:
    if not 'POSTFIX_ORIGIN' in str(kex):
        raise

destinations = list(hdest.values())

json.dump(sorted(destinations, key=lambda el: el['ui_name']), fp=sys.stdout)
