#!/usr/bin/env python3

#
# Copyright (C) 2022 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import json
import sys
import os
import agent
import mail
from agent.ldapclient import Ldapclient
from agent.ldapproxy import Ldapproxy

hdest = {}

try:
    dconf = Ldapproxy().get_domain(os.environ['POSTFIX_ORIGIN'])
    agent.assert_exp(dconf is not None) # Ensure the user domain exists
    dconf['hidden_users'] += mail.get_disabled_users() # Extend with mail-disabled users
    ldapclient = Ldapclient.factory(**dconf)

    for euser in ldapclient.list_users():
        hdest[euser['user']] = {
            'dtype': 'user',
            'name': euser['user'],
            'ui_name': euser['display_name'],
        }

    for egroup in ldapclient.list_groups():
        hdest[egroup['group']] = {
            'dtype': 'group',
            'name': egroup['group'],
            'ui_name': egroup['description'],
        }

except KeyError as kex:
    if not 'POSTFIX_ORIGIN' in str(kex):
        raise

destinations = list(hdest.values())

json.dump(sorted(destinations, key=lambda el: el['ui_name']), fp=sys.stdout)
