#!/bin/bash

#
# Copyright (C) 2023 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

exec 1>&2

if [[ -d tls-certs ]] ; then
    exit 0
fi

mkdir -vp tls-certs
systemctl --user start get-certificate.service
mv -vf dh.pem tls-certs/dh.pem
podman volume rm -f postfix-cert dovecot-cert
