#!/usr/bin/env python3

#
# Copyright (C) 2025 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import agent
import os
import sys

# Upgrade to new default value for bug NethServer/dev#7343
if os.getenv('POSTFIX_MILTERS') == 'inet:localhost:11332':
    agent.unset_env('POSTFIX_MILTERS') # rely on the container default
