#!/bin/bash

#
# Copyright (C) 2023 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

exec 1>&2

systemctl --user try-restart \
    dovecot.service \
    postfix.service \
    rspamd.service \
    clamav.service
