#!/usr/bin/env python3

#
# Copyright (C) 2022 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import json
import sys
import agent
import os

request = json.load(sys.stdin)
node_id = int(os.environ['NODE_ID'])
agent_id = os.environ['AGENT_ID']
module_uuid = os.environ['MODULE_UUID']

# Delete srv records in Redis for service discovery
with agent.redis_connect(privileged=True) as prdb:
    trx = prdb.pipeline()

    kimap = agent_id + "/srv/tcp/imap"
    trx.delete(kimap)

    ksubmission = agent_id + "/srv/tcp/submission"
    trx.delete(ksubmission)

    trx.execute()
