#!/bin/bash

#
# Copyright (C) 2023 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

exec 1>&2

domain_suffix=$(< mail_domain.txt)

podman run -i \
    --name=migrate_maildirs --replace --rm \
    --network=none \
    --log-driver=none \
    --env=DOVECOT_* \
    --volume=dovecot-data:/var/lib/vmail:z \
    "${MAIL_DOVECOT_IMAGE:?}" \
    ash -s "${domain_suffix,,}" <<'EOF'

# shellcheck shell=ash disable=SC3060,SC3028

# Utility function
ends_with_suffix() {
    echo "$1" | awk -F "${2}" '{ if(NF < 2) { exit(1) } }'
    return $?
}

# Regexp matching the domain suffix substring
rx_domain_suffix="${1//./\\.}"

# Migrate dict DB
sed -i -r "/@${rx_domain_suffix}(\/|\$)/ s/@${rx_domain_suffix}\b//g" shared-mailboxes.db

# Migrate mail home dirs
for entry in *; do
    if [ ! -d "${entry}" ]; then
        continue # ignore non-directory entries
    elif [ "${entry}" = root ] || [ "${entry}" = vmail ]; then
        # Do not rename, just fix ACLs and shared namespace
        ddest="${entry}"
    elif ends_with_suffix "${entry}" "@${1}"; then
        # Remove the domain suffix from the dir name:
        ddest="${entry%%@${1}}"

        # Skip bogus entries:
        if [ "${ddest}" = vmail ] || [ "${ddest}" = root ] || [ -z "${ddest}" ]; then
            echo "Bogus entry ignored: \`${entry}\`"
            continue
        fi

        # Backup of destination if it is already present:
        if [ -d "${ddest}" ]; then
            echo -n "Destination for \`${entry}\` already exists: "
            mv -v "${ddest}" "${ddest}.$RANDOM"
        fi

        # Mail home migration
        echo -n "Renamed "
        mv -v "${entry}" "${ddest}"
    else
        echo "Skipped migration of \`${entry}\`"
        continue # skip non-matching directories
    fi

    # Fix paths for shared namespace
    find "${ddest}" -type d -path "${ddest}/Maildir/shared/*@${1}" -print | (
        while read -r shared_entry ; do
            mv -vf "${shared_entry}" "${shared_entry%%@${1}}" || :
        done
    )

    # Fix IMAP acls: remove the domain suffix, remove ACLs for root, add "delete" flag to "full access"
    find "${ddest}" -name dovecot-acl -type f -print0 | xargs -r -0 -- sed -i -r \
        -e "s/@${rx_domain_suffix}\b//g" \
        -e "s/\bakeilprwts\b/akxeilprwts/g" \
        -e "/^user=root / d"

done

exit 0

EOF
