#!/usr/bin/env python3

#
# Copyright (C) 2023 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import sys
import os
import agent

configure_retval = agent.tasks.run(agent_id=os.environ['AGENT_ID'], action='configure-module', data={
    "user_domain": os.environ["POSTFIX_ORIGIN"],
    "hostname": os.environ["MAIL_HOSTNAME"],
})
agent.assert_exp(configure_retval['exit_code'] == 0, "The configure-module subtask failed!")
