#!/bin/bash

#
# Copyright (C) 2022 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

set -e    # exit immediately if an error occurs
exec 1>&2 # ensure any output is sent to stderr

# Rspamd stop/start, to rename the migrated Bayes DB

systemctl --user stop rspamd.service || :

podman run -i \
    --name=migrate_bayesdb --replace --rm \
    --network=none \
    --env=RSPAMD_* \
    --volume=rspamd-redis:/var/lib/redis:Z \
    --workdir=/var/lib/redis \
    "${MAIL_RSPAMD_IMAGE:?}" \
    mv -vf dump.rdb persistent.rdb || : # ignore non-existing file error

systemctl --user start rspamd.service
