#!/bin/bash

#
# Copyright (C) 2022 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

exec 1>&2

if [[ -n "${DOVECOT_DISABLED_USERS}" ]]; then
    systemctl --user reload dovecot.service
fi
