#!/usr/bin/env python3

#
# Copyright (C) 2022 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

import json
import sys
import agent
import os
import cluster.userdomains

config = {
    'user_domain': None,
    'hostname': os.environ.get('POSTFIX_HOSTNAME', None),
}

try:
    rdb = agent.redis_connect()
    udomain = cluster.userdomains.list_domains(rdb)[os.environ['POSTFIX_ORIGIN']]
    config['user_domain'] = udomain
except KeyError:
    pass

json.dump(config, fp=sys.stdout)
