#!/usr/bin/env python3

#
# Copyright (C) 2022 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import json
import sys
import agent
import os
import cluster.userdomains

config = {
    'user_domain': None,
    'hostname': os.environ.get('POSTFIX_HOSTNAME', None),
}

try:
    rdb = agent.redis_connect()
    udomain = cluster.userdomains.list_domains(rdb)[os.environ['POSTFIX_ORIGIN']]
    config['user_domain'] = udomain
except KeyError:
    pass

json.dump(config, fp=sys.stdout)
