#!/usr/bin/env python3

#
# Copyright (C) 2023 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import json
import sys
import agent
import os


request = json.load(sys.stdin)

bcc = request['bcc']

agent.set_env('POSTFIX_ALWAYS_BCC', bcc)
