#!/usr/bin/env python3

#
# Copyright (C) 2023 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import json
import sys
import mail
import socket
import agent

hostname = socket.getfqdn().lower()

try:
    mail_domain = hostname[hostname.index(".") + 1:]
except ValueError:
    mail_domain = ""

json.dump({
    'hostname': hostname,
    "mail_domain": mail_domain,
    "user_domains": mail.get_user_domains(agent.redis_connect()),
}, fp=sys.stdout)
