#!/usr/bin/env python3

#
# Copyright (C) 2023 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import json
import sys
import mail
import subprocess
import agent

try:
    hostname = subprocess.run(['hostname', '-f'], text=True, capture_output=True, check=True).stdout.strip()
    mail_domain = hostname[hostname.index(".") + 1:]
except ValueError:
    hostname = "myserver.example.org"
    mail_domain = "example.org"

json.dump({
    'hostname': hostname,
    "mail_domain": mail_domain,
    "user_domains": mail.get_user_domains(agent.redis_connect()),
}, fp=sys.stdout)
