name: "Publish images"

on:
  push:
    branches-ignore:
      - "renovate/**"

permissions:
  packages: write

jobs:
  publish-images:
    if: github.run_number > 1
    uses: NethServer/ns8-github-actions/.github/workflows/publish-branch.yml@v1
