name: Test module

on:
  workflow_dispatch:
    inputs:
      debug_shell:
        description: "Debug shell"
        required: true
        type: boolean
  workflow_run:
    workflows: ["Publish images"]
    types: [completed]

jobs:
  test:
    name: "Test"
    uses: NethServer/ns8-github-actions/.github/workflows/test-module.yml@refactor-testing
    with:
      debug_shell: ${{ github.event.inputs.debug_shell == 'true' }}
    secrets:
      do_token: ${{ secrets.do_token }}
