#!/usr/bin/env python3

#
# Copyright (C) 2022 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

import json
import sys
import os
import mail

rusers = mail.doveadm_query("user", {"userMask":"*"})

gquota = int(os.getenv("DOVECOT_QUOTA_MB", -1))

try:
    rquotas = mail.doveadm_query("quotaGet", {"allUsers":True})
except:
    rquotas = []

mailboxes = {}

for ouser in rusers['userList']:
    mailboxes[ouser] = {"user": ouser}

for oquota in rquotas:
    if not oquota['username'] in mailboxes:
        continue # unknown username, skip

    if oquota['type'] == 'STORAGE':
        if oquota['limit'] == '-':
            qlimit = None
        else:
            qlimit = int(oquota["limit"]) >> 10 # divide by 1024 to convert KBi to MBi

        mailboxes[oquota['username']]['quota'] = {
            "limit": qlimit,
            "value": int(oquota["value"]) >> 10,
            "percent": int(oquota["percent"]),
        }
        if mailboxes[oquota['username']]['quota']['limit'] != gquota:
            mailboxes[oquota['username']]['quota']['custom'] = True

sdb = mail.pcdb_connect(readonly=True)

for rforward in sdb.execute("""SELECT user, dest FROM userforwards WHERE user != dest""").fetchall():
    if not rforward['user'] in mailboxes:
        continue # unknown username, skip

    if not 'forward' in mailboxes[rforward['user']]:
        mailboxes[rforward['user']]['forward'] = {"destinations":[]}

    mailboxes[rforward['user']]['forward']['destinations'].append(mail.mailbox_to_destination(rforward['dest']))

for kforward in sdb.execute("""SELECT user, dest FROM userforwards WHERE user = dest""").fetchall():
    if not kforward['user'] in mailboxes:
        continue # unknown username, skip

    if not 'forward' in mailboxes[kforward['user']]:
        continue # no forwards, keepcopy is useless

    mailboxes[kforward['user']]['forward']['keepcopy'] = True

if 'vmail' in mailboxes:
    del mailboxes['vmail']

json.dump(list(mailboxes.values()), fp=sys.stdout, cls=mail.DestEncoder)
