#!/usr/bin/env python3

#
# Copyright (C) 2022 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import json
import sys
import agent
import mail
import os
from agent.ldapproxy import Ldapproxy
from agent.ldapclient import Ldapclient, LdapclientEntryNotFound

request = json.load(sys.stdin)

master_users = request['master_users']

domain = Ldapproxy().get_domain(os.environ['POSTFIX_ORIGIN'])
agent.assert_exp(domain is not None) # Ensure the user domain exists
oldap = Ldapclient.factory(**domain)

for muser in master_users:
    try: # ask Dovecot if user is valid
        _ = oldap.get_user(muser)["user"]
    except LdapclientEntryNotFound:
        agent.set_status('validation-failed')
        json.dump([{'field': 'master_users', 'parameter': 'master_users', 'value': muser, 'error':'user_not_found'}], fp=sys.stdout)
        sys.exit(2)

agent.set_env('DOVECOT_MASTER_USERS', ",".join(master_users))
agent.dump_env()
